//
//  UIColor+SportUpColors.swift
//
//  Generated by Zeplin on 3/23/17.
//  Copyright (c) 2017 Binary Blitz. All rights reserved. 
//

import UIKit

extension UIColor {
  func lighter(percentage: CGFloat = 0.1) -> UIColor {
    return self.colorWithBrightness(factor: 1 + abs(percentage))
  }

  func darker(percentage: CGFloat = 0.1) -> UIColor {
    return self.colorWithBrightness(factor: 1 - abs(percentage))
  }

  func colorWithBrightness(factor: CGFloat) -> UIColor {
    var hue: CGFloat = 0
    var saturation: CGFloat = 0
    var brightness: CGFloat = 0
    var alpha: CGFloat = 0

    if getHue(&hue, saturation: &saturation, brightness: &brightness, alpha: &alpha) {
      return UIColor(hue: hue, saturation: saturation, brightness: brightness * factor, alpha: alpha)
    } else {
      return self
    }
  }

	class var sportUpAquaMarine: UIColor {
		return UIColor(red: 50.0 / 255.0, green: 204.0 / 255.0, blue: 223.0 / 255.0, alpha: 1.0)
	}

	class var sportUpPaleGrey: UIColor {
		return UIColor(red: 247.0 / 255.0, green: 249.0 / 255.0, blue: 250.0 / 255.0, alpha: 1.0)
	}

  class var sportupBlueyGrey: UIColor {
    return UIColor(red: 154.0 / 255.0, green: 172.0 / 255.0, blue: 183.0 / 255.0, alpha: 1.0)
  }
}
